In [31]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
%matplotlib inline


In [68]:
words = open('newnames.txt', 'r').read().splitlines()
words

['SUSHIL',
 'SRIKRISHNA',
 'SANTOSH',
 'VIGNESH',
 'RAMYA',
 'CHARAN',
 'VINNY',
 'USHA',
 'SURYA ',
 'MEGHANA',
 'JAHNAVI',
 'NITHYASHREE',
 'KAUSHIK',
 'MAHESHWAR',
 'PREETHI',
 'SHASHIKANTH',
 'REETEKA',
 'JAHNAVI',
 'SUDHEER',
 'JAYANTH',
 'SAIMOULI',
 'ANURAG',
 'REVATHI',
 'UDAY',
 'HARSHITHA',
 'SRUTHI ',
 'MANIK',
 'AMRIT',
 'SAMAD',
 'FAHD ',
 'VISHNUPRIYA',
 'SUSHANK',
 'VARSHINI',
 'KARTHIKEYA',
 'LEKHYA',
 'SIDHANTH',
 'VARDHAN',
 'VAMSI',
 'ESHWAR',
 'RISHITHA',
 'OUCHITHYA',
 'SATHVIK',
 'PRASHANTI',
 'RAKESH ',
 'KARTHIKEYA',
 'SALMAN',
 'NITESH',
 'DHEERAJ',
 'AADARSH',
 'SNIGDHA',
 'SAHITHI',
 'SANTOSHI',
 'KRISHNA ',
 'RAHUL',
 'ZOYA']

In [69]:
chars = sorted(list(set(''.join(words))))
# chars = [char for char in chars if char != ' ']
chars

[' ',
 'A',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'Y',
 'Z']

In [70]:
len(chars)

24

In [71]:
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi

{' ': 1,
 'A': 2,
 'C': 3,
 'D': 4,
 'E': 5,
 'F': 6,
 'G': 7,
 'H': 8,
 'I': 9,
 'J': 10,
 'K': 11,
 'L': 12,
 'M': 13,
 'N': 14,
 'O': 15,
 'P': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'Y': 23,
 'Z': 24}

In [72]:
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: ' ', 2: 'A', 3: 'C', 4: 'D', 5: 'E', 6: 'F', 7: 'G', 8: 'H', 9: 'I', 10: 'J', 11: 'K', 12: 'L', 13: 'M', 14: 'N', 15: 'O', 16: 'P', 17: 'R', 18: 'S', 19: 'T', 20: 'U', 21: 'V', 22: 'W', 23: 'Y', 24: 'Z', 0: '.'}


In [73]:
block_size = 3 
X,Y = [],[]
for w in words :
#     print(w)
    context = [0] * block_size 
#     print(context)
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        
        print(''.join(itos[i] for i in context), '--->', itos[ix])
        Y.append(ix)
        context = context[1:] + [ix]
        
    

... ---> S
..S ---> U
.SU ---> S
SUS ---> H
USH ---> I
SHI ---> L
HIL ---> .
... ---> S
..S ---> R
.SR ---> I
SRI ---> K
RIK ---> R
IKR ---> I
KRI ---> S
RIS ---> H
ISH ---> N
SHN ---> A
HNA ---> .
... ---> S
..S ---> A
.SA ---> N
SAN ---> T
ANT ---> O
NTO ---> S
TOS ---> H
OSH ---> .
... ---> V
..V ---> I
.VI ---> G
VIG ---> N
IGN ---> E
GNE ---> S
NES ---> H
ESH ---> .
... ---> R
..R ---> A
.RA ---> M
RAM ---> Y
AMY ---> A
MYA ---> .
... ---> C
..C ---> H
.CH ---> A
CHA ---> R
HAR ---> A
ARA ---> N
RAN ---> .
... ---> V
..V ---> I
.VI ---> N
VIN ---> N
INN ---> Y
NNY ---> .
... ---> U
..U ---> S
.US ---> H
USH ---> A
SHA ---> .
... ---> S
..S ---> U
.SU ---> R
SUR ---> Y
URY ---> A
RYA --->  
YA  ---> .
... ---> M
..M ---> E
.ME ---> G
MEG ---> H
EGH ---> A
GHA ---> N
HAN ---> A
ANA ---> .
... ---> J
..J ---> A
.JA ---> H
JAH ---> N
AHN ---> A
HNA ---> V
NAV ---> I
AVI ---> .
... ---> N
..N ---> I
.NI ---> T
NIT ---> H
ITH ---> Y
THY ---> A
HYA ---> S
YAS ---> H
ASH ---> R
SHR ---> E

In [74]:
X = torch.tensor(X)
Y = torch.tensor(Y)



In [75]:
X.dtype , X.shape , Y.dtype, Y.shape

(torch.int64, torch.Size([442, 3]), torch.int64, torch.Size([442]))

In [76]:
W1 = torch

In [77]:
X = torch.tensor(X, dtype=torch.long)

/tmp/ipykernel_11674/3081328166.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.long)


In [78]:
C = torch.randn((25,2))
C



tensor([[-1.1641, -0.5828],
        [-0.9082, -0.6994],
        [-0.9441, -1.2614],
        [-0.0873,  0.2022],
        [ 1.6010,  0.0326],
        [ 0.3696, -0.6310],
        [-0.0757, -0.5886],
        [ 0.1676,  0.3631],
        [ 1.3738,  0.3118],
        [ 1.3499,  1.3921],
        [-0.1024, -0.1119],
        [ 0.5364, -1.0807],
        [-1.4025,  0.5786],
        [ 1.5578,  0.5050],
        [ 0.7797, -0.5947],
        [-1.2363, -1.2395],
        [ 0.2061,  0.0233],
        [-1.3436, -1.1453],
        [ 0.4372, -0.2182],
        [-0.4049,  0.5465],
        [ 0.3035, -0.7777],
        [-0.2695,  0.1013],
        [ 0.3145,  0.9509],
        [ 0.3699, -2.5497],
        [-0.1759,  0.7542]])

In [79]:
X_clamped = torch.clamp(X, 0, C.size(0) - 1)

In [80]:
emb = C[X_clamped]

In [81]:
emb.shape

torch.Size([442, 3, 2])

In [82]:
W1 = torch.randn((6,100))
b1 = torch.randn(100)

In [83]:
h = torch.tanh(emb.view(-1,6) @ W1 + b1)
h

tensor([[-0.9997,  0.1516, -0.9033,  ..., -0.9911, -0.9998, -1.0000],
        [-0.7809,  0.9717,  0.0027,  ..., -0.8109, -0.9991, -0.9999],
        [-0.7296,  0.9505, -0.5123,  ..., -0.9420, -0.9337, -0.8816],
        ...,
        [-0.9999,  0.1085, -0.9985,  ..., -0.9771, -0.9870, -0.9699],
        [-0.6802, -0.9217, -0.9963,  ...,  0.4880, -0.9999, -1.0000],
        [-0.9950,  0.4682,  0.4964,  ..., -0.9998, -1.0000, -1.0000]])

In [84]:
h.shape

torch.Size([442, 100])

In [85]:
W2 = torch.randn((100,25))
b2 = torch.randn(25)

In [86]:
logits = h @ W2 + b2

In [87]:
logits

tensor([[ -8.4506,   0.2132,   1.6987,  ...,  -7.2957,   0.7031,   7.3932],
        [-11.9146, -11.0139,   6.1548,  ...,   1.7371,  -3.9089,  18.6334],
        [-13.0080,  -3.1812,   6.2986,  ...,   6.7058,   6.3734,  14.4214],
        ...,
        [-12.7974,   4.9627,   0.5583,  ...,  -7.4860,  -8.6930,   5.4951],
        [-18.7515,   7.3650,   1.2386,  ...,  -7.9489,   4.9688,   0.8912],
        [ -3.2917,   7.1035,   3.5220,  ...,  -4.3467,  16.8166,  16.0399]])

In [88]:
logits.shape

torch.Size([442, 25])

In [89]:
counts = logits.exp()
counts



tensor([[2.1378e-04, 1.2376e+00, 5.4668e+00,  ..., 6.7844e-04, 2.0200e+00,
         1.6250e+03],
        [6.6918e-06, 1.6472e-05, 4.7099e+02,  ..., 5.6811e+00, 2.0063e-02,
         1.2371e+08],
        [2.2422e-06, 4.1536e-02, 5.4378e+02,  ..., 8.1710e+02, 5.8604e+02,
         1.8329e+06],
        ...,
        [2.7681e-06, 1.4298e+02, 1.7477e+00,  ..., 5.6090e-04, 1.6776e-04,
         2.4349e+02],
        [7.1835e-09, 1.5798e+03, 3.4508e+00,  ..., 3.5306e-04, 1.4385e+02,
         2.4382e+00],
        [3.7190e-02, 1.2162e+03, 3.3851e+01,  ..., 1.2949e-02, 2.0107e+07,
         9.2480e+06]])

In [90]:
counts.shape

torch.Size([442, 25])

In [91]:
prob = counts/ counts.sum()
prob

tensor([[1.5748e-17, 9.1168e-14, 4.0272e-13,  ..., 4.9978e-17, 1.4880e-13,
         1.1971e-10],
        [4.9296e-19, 1.2134e-18, 3.4696e-11,  ..., 4.1851e-13, 1.4780e-15,
         9.1132e-06],
        [1.6518e-19, 3.0598e-15, 4.0059e-11,  ..., 6.0193e-11, 4.3171e-11,
         1.3502e-07],
        ...,
        [2.0391e-19, 1.0533e-11, 1.2875e-13,  ..., 4.1320e-17, 1.2358e-17,
         1.7937e-11],
        [5.2918e-22, 1.1638e-10, 2.5421e-13,  ..., 2.6009e-17, 1.0597e-11,
         1.7961e-13],
        [2.7397e-15, 8.9595e-11, 2.4937e-12,  ..., 9.5392e-16, 1.4812e-06,
         6.8126e-07]])

In [92]:
Y

tensor([18, 20, 18,  8,  9, 12,  0, 18, 17,  9, 11, 17,  9, 18,  8, 14,  2,  0,
        18,  2, 14, 19, 15, 18,  8,  0, 21,  9,  7, 14,  5, 18,  8,  0, 17,  2,
        13, 23,  2,  0,  3,  8,  2, 17,  2, 14,  0, 21,  9, 14, 14, 23,  0, 20,
        18,  8,  2,  0, 18, 20, 17, 23,  2,  1,  0, 13,  5,  7,  8,  2, 14,  2,
         0, 10,  2,  8, 14,  2, 21,  9,  0, 14,  9, 19,  8, 23,  2, 18,  8, 17,
         5,  5,  0, 11,  2, 20, 18,  8,  9, 11,  0, 13,  2,  8,  5, 18,  8, 22,
         2, 17,  0, 16, 17,  5,  5, 19,  8,  9,  0, 18,  8,  2, 18,  8,  9, 11,
         2, 14, 19,  8,  0, 17,  5,  5, 19,  5, 11,  2,  0, 10,  2,  8, 14,  2,
        21,  9,  0, 18, 20,  4,  8,  5,  5, 17,  0, 10,  2, 23,  2, 14, 19,  8,
         0, 18,  2,  9, 13, 15, 20, 12,  9,  0,  2, 14, 20, 17,  2,  7,  0, 17,
         5, 21,  2, 19,  8,  9,  0, 20,  4,  2, 23,  0,  8,  2, 17, 18,  8,  9,
        19,  8,  2,  0, 18, 17, 20, 19,  8,  9,  1,  0, 13,  2, 14,  9, 11,  0,
         2, 13, 17,  9, 19,  0, 18,  2, 

In [93]:
len(Y)

442

In [94]:
loss = -prob[torch.arange(46), Y].log().mean()

IndexError: shape mismatch: indexing tensors could not be broadcast together with shapes [46], [442]

In [95]:
loss

tensor(0.6002, grad_fn=<NllLossBackward0>)

In [96]:
parameters = [C, W1,W2,b1,b2]

sum(p.nelement() for p in parameters)

3275

In [97]:
F.cross_entropy(logits, Y)

tensor(16.9543)

In [101]:
for p in parameters:
    p.requires_grad = True

In [100]:
g = torch.Generator().manual_seed(2147483647) # for reproducibility
C = torch.randn((25, 2), generator=g)
W1 = torch.randn((6, 100), generator=g)
b1 = torch.randn(100, generator=g)
W2 = torch.randn((100, 25), generator=g)
b2 = torch.randn(25, generator=g)
parameters = [C, W1, b1, W2, b2]

In [102]:
X.shape

torch.Size([442, 3])

In [103]:
C.shape

torch.Size([25, 2])

In [104]:
Y_clamped = torch.clamp(torch.tensor(Y, dtype=torch.long), 0, C.size(0) - 1)

/tmp/ipykernel_11674/1924134891.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  Y_clamped = torch.clamp(torch.tensor(Y, dtype=torch.long), 0, C.size(0) - 1)


In [105]:
for _ in range(100000):
    #forward pass 
    emb = C[X_clamped]
    h = torch.tanh(emb.view(-1,6) @ W1 + b1)
    logits = h @ W2 + b2
    loss = F.cross_entropy(logits , Y_clamped)
#     print(f"loss : {loss.item()}")
    
    #backward pass 
    for p in parameters :
        p.grad = None 
    loss.backward()
    
    #update 
    for p in parameters:
        p.data += -0.1* p.grad
print(f"loss : {loss.item()}")

    

loss : 0.6657325625419617


In [106]:
# sample from the model
g = torch.Generator().manual_seed(2147483647 + 10)

for _ in range(20):
    
    out = []
    context = [0] * block_size # initialize with all ...
    while True:
      emb = C[torch.tensor([context])] # (1,block_size,d)
      h = torch.tanh(emb.view(1, -1) @ W1 + b1)
      logits = h @ W2 + b2
      probs = F.softmax(logits, dim=1)
      ix = torch.multinomial(probs, num_samples=1, generator=g).item()
      context = context[1:] + [ix]
      out.append(ix)
      if ix == 0:
        break
    
    print(''.join(itos[i] for i in out))

MAHESHWAR.
REETHI.
DHEERAJ.
ESH .
JAYANTOSH.
REETEKA.
HARAN.
RISHNA.
ESHWAR.
REETEKA.
KRISHITHA.
SHASHREETHI .
JAHNAVI.
JAHNAVI.
PRASHVA.
KARTHI.
JAHNA.
RISHNA .
RAHUL.
REETEKA.
